style(legend): Ajustements de style
infra-geo-ouverte/igo2-quebec pull request #40
Opened 2023-06-07 13:17 UTC by mneige

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2-quebec/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
Le dialogue de la légende n'a pas de barre de défilement et en mode menu activé elle s'affiche dans le menu

**What is the new behavior?**
Le dialogue s'affiche dans la carte et a une barre de défilement

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications:

**Other information**:

2023-08-02 13:54 UTC, alecarn requested changes

2023-08-02 13:54 UTC, alecarn commented on src/assets/legends/legend-1/legende-1.html
> +<link type="text/css" rel="stylesheet" href="../legend.css">
A quoi ça sert ce HTML, je ne vois aucune importation dans l'application?
Même chose pour le fichier 'legend.css', si ce n'est pas utilisé on devrait le supprimer.

2023-08-02 15:13 UTC, alecarn requested changes

2023-08-02 15:13 UTC, alecarn commented on src/assets/legends/legend/legende.html
> +            "html": "<div class='iframe-legend-container'><iframe class='iframe-legend embed-responsive' title='Légende' style='overflow:hidden;border:none;width:100%;height:176px;' loading='lazy'  s
- Je ne vois aucune classe `embed-responsive`
- On retrouve du style au niveau de l'attribut style et aussi via la classe `iframe-legend`, le quel est le bon style?
- On spécifie un html qui n'existe pas `assets/legends/legende-stations.html`

2023-08-02 15:13 UTC, alecarn commented on src/assets/legends/legend/legende.html
> +    <div><img src="classe2.svg">classe2</div>
Les images svg n'existent pas?

2023-08-02 15:13 UTC, alecarn commented on src/app/pages/portal/portal.component.scss
> +    max-height: calc($portal-height-hasFooter-hasHeader - $map-buttons-height); // see portal variables to replace $map-buttons-height-xxxx
Les deux commentaires ci-dessus, ne semble plus valide. On référence `$top-legend-dialog` qui ne semble pas utilisé nul part et `$map-buttons-height-xxxx`. Il faudrait soit supprimer les commentaires ou s'assurer de les maintenirs dans le temps.

2023-08-02 16:10 UTC, alecarn commented on src/assets/legends/legend/legende.html
> +<!-- Pour utiliser la légende HTML, dans le contexte, ajouter ceci dans la couche, au même niveau que "title":
Comme tu m'as indiqué via le chat, on a la [wiki sur github]([https://github.com/infra-geo-ouverte/igo2-quebec/wiki/Légende](https://github.com/infra-geo-ouverte/igo2-quebec/wiki/L%C3%A9gende)) ce qui est très bien. Si ces fichiers sont seulement des modèle qui sert a la documentation, je proposerais de créer un nouveau dossier `wiki/legend` dans le root du projet où l'on pourrait mettre des modèles d'example sans affecter la qualité de notre code base.

2023-08-07 14:41 UTC, mneige commented on src/assets/legends/legend.css
> +}
puisque la légende est en iframe, ce n'est pas le body de l'application mais bien le body de la légende

2023-08-07 15:24 UTC, alecarn commented on src/assets/legends/legend.css
> +}
Ha d'accord, intéressant j'aurais cru que le body de l'application serait affecté. Bon à savoir merci

2023-08-09 13:44 UTC, mneige commented on src/assets/legends/legend/legende.html
> +<!-- Pour utiliser la légende HTML, dans le contexte, ajouter ceci dans la couche, au même niveau que "title":
Bonne idée je vais aussi intégrer les templates dans la documentation

2023-08-09 13:45 UTC, mneige commented on src/wiki
oui, une erreur de push!

2023-09-22 19:29 UTC, mneige commented on src/assets/legends/legend-1/legende-1.html
> +<link type="text/css" rel="stylesheet" href="../legend.css">
https://github.com/infra-geo-ouverte/igo2-quebec/pull/40/commits/991f7d46e4602c8a2dcba501b83dc81b2fdbfcd6
Les fichiers ont été retirés et seront remis dans une demo

2023-09-22 19:30 UTC, mneige commented on src/assets/legends/legend.css
> +}
Comme mentionné plus haut, non nécessaire dans le contexte d'un iframe

2023-09-22 19:35 UTC, mneige commented on src/app/pages/portal/portal.component.scss
> +    max-height: calc($portal-height-hasFooter-hasHeader - $map-buttons-height); // see portal variables to replace $map-buttons-height-xxxx
https://github.com/infra-geo-ouverte/igo2-quebec/pull/40/files#diff-4eb5bae113bc58aac604af1dfa39b7eb047fc6da2d074700f488108a7bf15bddR28 c'est à l'utilisateur de le modifier selon sa config, comme spécifié dans le commentaire

2023-09-22 19:35 UTC, mneige commented on src/assets/legends/legend/legende.html
> +    <div><img src="classe2.svg">classe2</div>
je les ai supprimés du tronc commun

2023-09-22 19:43 UTC, mneige commented on src/assets/legends/legend/legende.html
> +            "html": "<div class='iframe-legend-container'><iframe class='iframe-legend embed-responsive' title='Légende' style='overflow:hidden;border:none;width:100%;height:176px;' loading='lazy'  s
ce sont des styles iframe

2023-09-25 14:59 UTC, alecarn approved these changes

2023-09-25 14:59 UTC, alecarn commented on src/wiki
Le fichier est vide, on pourrait le supprimer s'il ne sert a rien

2023-09-25 15:42 UTC, merged