feat(feature-info): use igo-feature-details and set custom style
infra-geo-ouverte/igo2-quebec pull request #45
Opened 2023-10-31 19:59 UTC by aziz-access

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2-quebec/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications:

**Other information**:

2023-11-01 11:38 UTC, alecarn requested changes

2023-11-01 11:38 UTC, alecarn commented on src/app/pages/portal/panels/feature/feature-info/feature-info.component.html
> +  </app-feature-details-->
Supprimer le code commenté

2023-11-01 11:38 UTC, alecarn commented on src/app/pages/portal/panels/feature/feature-info/feature-info.component.html
> +  </igo-feature-details>
Vu qu'on a réussit a utiliser la composante de la librairie, il faudrait supprimer les fichiers dans ce projet qui ont été dupliquer de igo2-lib.

2023-11-01 11:38 UTC, alecarn commented on src/app/pages/portal/panels/feature/feature-info/feature-info.module.ts
> +import { IgoFeatureModule as IgoFeatureModules } from '@igo2/geo';
On pourrait renommer le `IgoFeatureModule` de IGO2-QUEBEC  `AppFeatureModule` et conserver la nomenclature de la librairie.
```suggestion
import { AppFeatureModule } from '../feature.module';
import { IgoFeatureModule } from '@igo2/geo';
```

2023-11-01 14:44 UTC, alecarn requested changes

2023-11-01 14:44 UTC, alecarn commented on src/app/pages/portal/panels/feature/feature-details/feature-details.module.ts
>  export class IgoFeatureDetailsModule {}
Renommer le module pour enlever le préfix `Igo`.  
Je crois qu'on a seulement le `feature-custom-details` dans ce dossier?  Si oui, on pourrait aussi renommer le dossier `feature-custom-details` et le module aussi?

2023-11-01 14:55 UTC, aziz-access commented on src/app/pages/portal/panels/feature/feature-details/feature-details.module.ts
>  export class IgoFeatureDetailsModule {}
ok, oui, nous pouvons renommer le dossier en `custom-component` or `shared-component`, pour tous les composants personnalisés.

2023-11-01 14:58 UTC, alecarn commented on src/app/pages/portal/panels/feature/feature-details/feature-details.module.ts
>  export class IgoFeatureDetailsModule {}
Je conserverais la nommenclature `feature-custom-details` vu que l'objectif de cette composante n'est pas très clair pour moi

2023-11-01 14:59 UTC, aziz-access commented on src/app/pages/portal/panels/feature/feature-details/feature-details.module.ts
>  export class IgoFeatureDetailsModule {}
ok

2023-11-02 11:34 UTC, alecarn requested changes

2023-11-02 11:34 UTC, alecarn commented on src/app/pages/portal/panels/feature/feature-info/feature-info.component.scss
> +    margin: 2em auto;
Pourquoi utiliser l'unité `em` au lieu de `px`?

2023-11-02 11:34 UTC, alecarn commented on src/app/pages/portal/panels/feature/feature-info/feature-info.component.scss
> +          font: normal 16px/24px 'Open Sans', sans-serif;
Qu'est-ce que ça représente comme valeur `normal 16px/24px`?

2023-11-02 12:39 UTC, aziz-access commented on src/app/pages/portal/panels/feature/feature-info/feature-info.component.scss
> +          font: normal 16px/24px 'Open Sans', sans-serif;
> Qu'est-ce que ça représente comme valeur `normal 16px/24px`?

C'est le raccourci pour les différentes propriétés liées aux font: 
```
font-weight: normal;
font-size: 16px;
line-height: 24px;
```

2023-11-02 12:49 UTC, aziz-access commented on src/app/pages/portal/panels/feature/feature-info/feature-info.component.scss
> +    margin: 2em auto;
px: mesure statique.
em: mesures relatives.
em: est plus utile si la taille de l'écran est modifiée (mobile, tablette...)

2023-11-02 15:47 UTC, alecarn approved these changes

2023-11-02 15:49 UTC, merged

2023-11-03 19:47 UTC, mneige commented
Il faut réviser l'apparence et le style en mode mobile. 
1 - le query ne s'affiche pas
![image](https://github.com/infra-geo-ouverte/igo2-quebec/assets/90412486/1f50dedf-39fb-4459-a061-4d6dfd1e5dc6)

2- le X de fermer n'est pas bien aligné
![image](https://github.com/infra-geo-ouverte/igo2-quebec/assets/90412486/331afd0d-48a5-47eb-a557-076bd3623755)

2023-11-03 19:49 UTC, mneige commented
le style du tooltip doit être ajusté dans le custom feature details
![image](https://github.com/infra-geo-ouverte/igo2-quebec/assets/90412486/7ee50515-b6aa-44fd-9aec-7ca7b8c40216)

2023-11-03 19:56 UTC, mneige commented
En mode mobile, il est impossible de baisser le panneau avec la flèche