Cleanup
infra-geo-ouverte/igo2-quebec pull request #51
Opened 2024-01-25 22:19 UTC by pelord

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2-quebec/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications:

**Other information**:

2024-01-26 15:09 UTC, alecarn requested changes
Good job @pelord 💪

2024-01-26 15:09 UTC, alecarn commented on src/app/app.component.ts
> +      .get(this.configService.getConfig('title', ''))
Pourquoi qu'on lui ajouter une valeur par défaut. Ça va by passer notre condition `if (title)` dans le subscribe et actionner par défaut le changement de title?

2024-01-26 15:09 UTC, alecarn commented on src/environments/environment.ts
> +        searchUrl: 'https://geoegl.msp.gouv.qc.ca/apis/icherche',
Pourquoi hardcoder la source du url?

2024-01-26 15:09 UTC, alecarn commented on src/app/app.component.ts
> +    this.hasMenu = this.configService.getConfig('hasMenu', false);
C'est meveilleux cette nouvelle gestion de config 🥇

2024-01-26 15:09 UTC, alecarn commented on src/app/app.module.ts
> -    provideSearchSourceService(),
Tous les autres providers n'étaient pas utiliser?

2024-01-26 15:09 UTC, alecarn commented on src/app/app.module.ts
> +      useValue: { appearance: 'fill' }
C'est déjà le défaut dans Angular, pas besoin de le redéfinir

2024-01-26 15:09 UTC, alecarn commented on src/app/app.module.ts
>      FooterModule,
FooterModule et GestureModule, est-ce qu'ils sont nécessaire?

2024-01-26 15:15 UTC, alecarn commented
@pelord, j'ai remarqué une erreur dans VsCode par rapport au `MenuModule` qui me mène vers le `MapComponent`. Cette composante n'est inclu dans aucun module, on supprime?

2024-01-26 15:18 UTC, alecarn commented
@pelord, j'ai remarqué une erreur dans VsCode par rapport au `MenuModule `qui me mène vers le `MapComponent`. Cette composante est déclarée dans deux modules, `MapModule` et `MenuModule`. On pourrait changer la déclaration du `MenuModule `pour qu'il importe le `MapModule `à la place

2024-01-26 17:50 UTC, LAMM26 commented on src/app/app.module.ts
> -    provideSearchSourceService(),
Il y a la méthode setWorkspaces de SearchSourceService qui est en erreut. Il faudrait le conserver? 
![image](https://github.com/infra-geo-ouverte/igo2-quebec/assets/83651899/d6042782-ad77-47ca-9ffd-2646ee40e1a4)

2024-01-26 18:52 UTC, pelord commented on src/app/app.module.ts
> -    provideSearchSourceService(),
Tu as raison. J'ai pas poussé mon fixe dans la lib encore..mais ça va être ok avec le fix. Bien vu

2024-01-26 19:57 UTC, pelord commented on src/app/app.component.ts
> +      .get(this.configService.getConfig('title', ''))
bien vu.

2024-01-26 20:12 UTC, pelord commented on src/app/app.module.ts
>      FooterModule,
aucune idée pour FooterModule

2024-01-26 20:12 UTC, pelord commented on src/app/app.module.ts
>      FooterModule,
@mneige peux tu valider?

2024-01-26 20:12 UTC, pelord commented on src/app/app.module.ts
> -    provideSearchSourceService(),
j'ai repris la syntaxe de l'assemblage.. igo2.. n'étant plus la, je me suis dit qu'ils n'étaient plus nécessaires!

2024-01-26 20:12 UTC, pelord commented on src/app/app.module.ts
> -    provideSearchSourceService(),
@LAMM26  https://github.com/infra-geo-ouverte/igo2-lib/pull/1609

2024-01-26 20:12 UTC, pelord commented on src/app/app.module.ts
> +      useValue: { appearance: 'fill' }
ok.

2024-01-26 20:12 UTC, pelord commented on src/environments/environment.ts
> +        searchUrl: 'https://geoegl.msp.gouv.qc.ca/apis/icherche',
j'ai commité ma config par erreur.

2024-01-26 21:28 UTC, pelord commented
@LAMM26 @mneige @alecarn 
Pourquoi il y a un duplicat du searchState? Pourquoi ne pas utiliser celui de la lib?

2024-01-29 13:04 UTC, alecarn commented
> @LAMM26 @mneige @alecarn Pourquoi il y a un duplicat du searchState? Pourquoi ne pas utiliser celui de la lib?
Bonne question, s'il n'y a pas de différence dans la logique d'affaire on pourrait le supprimer et remplacer par celui de la lib.

Pour ton info, on a fait certaine analyse #44  et #46  sur ce type de divergence. Malheureusement les conclusions ne sont pas documenté mais dans certain cas, on a décidé de conserver les divergences vu qu'il y avait des différences dans la logique d'affaire

2024-02-07 15:06 UTC, mneige approved these changes

2024-02-07 15:07 UTC, mneige commented on src/app/app.module.ts
>      FooterModule,
Footermodule oui pour faire un footer de la map, c'est une config. Gesture c'était pour certains comportements mobiles

2024-02-07 15:13 UTC, mneige reviewed
Quand la légende ne s'affiche pas dans le panneau latéral elle a perdu son positionnement. Elle est maintenant centrée au lieu d'être au-dessus des boutons de la carte.

2024-02-07 15:38 UTC, mneige commented
> @LAMM26 @mneige @alecarn Pourquoi il y a un duplicat du searchState? Pourquoi ne pas utiliser celui de la lib?

Simplement pour pouvoir le personnaliser mais on peut pointer vers la lib, c'est au besoin. Ou y ajouter des configs dans la lib

2024-03-18 18:55 UTC, merged